language: ruby
rvm:
- 2.3
- 2.4
- 2.5
before_install:
- gem install bundler -v 1.16.1
deploy:
  provider: rubygems
  api_key:
    secure: k231CjNqay+C/TLftBdXcmfH3M/yW0BdpQEMIvkYatDLtB1LmzMkXFsibYShJApp4LC0l9vE9KvUdrzVR4LDmX024wsjfFurIzkLrRnvqSGIMQsRd7f8Fk3rhzctXRSY7zfJPC11/eS+X5Xl/U79/xVRRf1AYXcRBAndG7uGpkFIuX9nhLX3LaFO3Kxn9l1bmuXyIAOwyPLZNHY+PUomSKnEkHpCg34BlhJThVkrgrh/LPkAX36wvHX3PJc4lTx47r9Gj99bq1GBby7cRFsPYShYtgdeM7f6g2MhGJma+WlTupCiCOb5+tSjoeze1EJ3knSd3+Tpaz4s9b0ukiV212XQjjWaf3hwlWJefj9feCEOIoIhqYBLJ7iArNxYcHVl0VqFg0cixpQZkUH0IRHhi9C7mhfxNf9kK8NbYl3ljRSLjN7LeM0ifE7k6k7vgiwdeZl3Ik2/kTasOufc33WNi/yQcKG2kQOZ3Nf/F+TyN9CSkSOo7BP10ZtIDs4xOeLZ3TmYAOXDWi4D2909dS4MJtTO1e6MMinwJnz+P6H51O7zKDagMy/UVlyTS/UpX/+YSuFZFjfZQFmgrt8wMsuOf0COcMJVJGdHPMYgVU8hJZ5DZ25TBvR/8xf6xNO8wbkqm90rEEh9dDSkQ41i/iGb5PYRTvMflJhtJTbTxwMeJ/U=
  gem: pretty_puts
  on:
    tags: true
    repo: jutonz/pretty_puts
